
-- Seed Data for Products
-- Clears existing data to avoid duplicates if run multiple times (optional, be careful in production)
-- TRUNCATE TABLE public.products; 

INSERT INTO public.products (product_name, product_category, product_tagline, product_description, showcase_image, info_image, mrp, net_weight, total_stock, quantity_variants)
VALUES
-- Ready To Eat
('Kadapa Kaaram', 'ready-to-eat', 'కడప కారం', 'A fiery and flavorful spice blend from the Kadapa region, known for its perfect balance of heat and taste. Made with carefully selected red chilies and traditional spices.', './images/products/kadapa-kaaram.jpg', '/images/products/kadapa-kaaram-detail.jpg', 150, '250g', 100, '[{"quantity": "250g", "price": 150, "mrp": 150, "stock": 100}]'),
('Nalla Kaaram', 'ready-to-eat', 'నల్ల కారం', 'Premium black pepper powder blend that adds warmth and depth to any dish. Rich in antioxidants and known for its digestive properties.', './images/products/nalla-kaaram.jpg', '/images/products/nalla-kaaram-detail.jpg', 160, '250g', 100, '[{"quantity": "250g", "price": 160, "mrp": 160, "stock": 100}]'),
('Kandi Podi', 'ready-to-eat', 'కంది పొడి', 'Traditional lentil-based spice powder that''s protein-rich and flavorful. Perfect for mixing with rice and ghee for a nutritious meal.', './images/products/kandi-podi.jpg', '/images/products/kandi-podi-detail.jpg', 140, '250g', 100, '[{"quantity": "250g", "price": 140, "mrp": 140, "stock": 100}]'),
('Godhuma Kaaram', 'ready-to-eat', 'గోధుమ కారం', 'Roasted wheat-based spice powder with aromatic spices. A healthy and wholesome option that adds texture and flavor to your meals.', './images/products/godhuma-kaaram.jpg', '/images/products/godhuma-kaaram-detail.jpg', 130, '250g', 100, '[{"quantity": "250g", "price": 130, "mrp": 130, "stock": 100}]'),
('Karivepaku Podi', 'ready-to-eat', 'కరివేపాకు పొడి', 'Fresh curry leaves dried and ground with traditional spices. Adds authentic South Indian aroma and is known for its health benefits.', './images/products/karivepaku-podi.jpg', '/images/products/karivepaku-podi-detail.jpg', 150, '250g', 100, '[{"quantity": "250g", "price": 150, "mrp": 150, "stock": 100}]'),
('Palli Dhaniya Podi', 'ready-to-eat', 'పల్లి ధనియా పొడి', 'A unique blend of roasted groundnuts and coriander seeds. Rich in protein and adds a nutty, aromatic flavor to rice and rotis.', './images/products/palli-dhaniya-podi.jpg', '/images/products/palli-dhaniya-podi-detail.jpg', 145, '250g', 100, '[{"quantity": "250g", "price": 145, "mrp": 145, "stock": 100}]'),
('Tamalapaaku Kaaram', 'ready-to-eat', 'తమలపాకు కారం', 'Bay leaf spice powder that adds a distinctive aroma and flavor. Used traditionally in Telugu cuisine for its medicinal properties.', './images/products/tamalapaaku-kaaram.jpg', '/images/products/tamalapaaku-kaaram-detail.jpg', 155, '250g', 100, '[{"quantity": "250g", "price": 155, "mrp": 155, "stock": 100}]'),
('Sambar Premix', 'ready-to-eat', 'సాంబార్ ప్రీమిక్స్', 'Ready-to-use sambar masala powder with the perfect balance of tangy and spicy flavors. Makes authentic sambar in minutes.', './images/products/sambar-premix.jpg', '/images/products/sambar-premix-detail.jpg', 120, '250g', 100, '[{"quantity": "250g", "price": 120, "mrp": 120, "stock": 100}]'),
('Velluli Kaaram', 'ready-to-eat', 'వెల్లుల్లి కారం', 'Fresh garlic dried and ground with aromatic spices. Known for its health benefits and bold flavor that enhances any dish.', './images/products/velluli-kaaram.jpg', '/images/products/velluli-kaaram-detail.jpg', 160, '250g', 100, '[{"quantity": "250g", "price": 160, "mrp": 160, "stock": 100}]'),
('Idli Podi', 'ready-to-eat', 'ఇడ్లీ పొడి', 'The classic accompaniment for idli and dosa. A perfect blend of lentils, chilies, and spices ground to perfection.', './images/products/idli-podi.jpg', '/images/products/idli-podi-detail.jpg', 135, '250g', 100, '[{"quantity": "250g", "price": 135, "mrp": 135, "stock": 100}]'),
('Konaseema Kaaram', 'ready-to-eat', 'కోనసీమ కారం', 'A special spice blend from the Konaseema region, known for its unique flavor profile and traditional preparation methods.', './images/products/konaseema-kaaram.jpg', '/images/products/konaseema-kaaram-detail.jpg', 165, '250g', 100, '[{"quantity": "250g", "price": 165, "mrp": 165, "stock": 100}]'),
('Chutney Premix', 'ready-to-eat', 'చట్నీ ప్రీమిక్స్', 'Ready-to-use chutney powder that makes instant chutneys. Just add water or oil for a quick and delicious accompaniment.', './images/products/chutney-premix.jpg', '/images/products/chutney-premix-detail.jpg', 125, '250g', 100, '[{"quantity": "250g", "price": 125, "mrp": 125, "stock": 100}]'),
('Palli Kaaram', 'ready-to-eat', 'పల్లి కారం', 'Roasted groundnut spice powder that''s protein-rich and flavorful. Perfect with idli, dosa, or mixed with rice and ghee.', './images/products/palli-kaaram.jpg', '/images/products/palli-kaaram-detail.jpg', 140, '250g', 100, '[{"quantity": "250g", "price": 140, "mrp": 140, "stock": 100}]'),

-- Ready To Cook
('Malabar Parota', 'ready-to-cook', 'మలబార్ పరోటా', 'Authentic Kerala-style layered parota made with premium flour and traditional techniques. Soft, flaky layers that separate beautifully when cooked. Perfect with curry or dal.', './images/products/malabar-parota.jpg', '/images/products/malabar-parota-detail.jpg', 80, '5 pcs', 100, '[{"quantity": "5 pcs", "price": 80, "mrp": 80, "stock": 100}]'),
('Wheat Chapathi', 'ready-to-cook', 'గోధుమ చపాతీ', 'Soft, wholesome wheat chapathi made from carefully selected wheat flour. Perfect balance of nutrition and taste, ideal for wrapping curries or enjoying with dal and vegetables.', './images/products/wheat-chapathi.jpg', '/images/products/wheat-chapathi-detail.jpg', 60, '5 pcs', 100, '[{"quantity": "5 pcs", "price": 60, "mrp": 60, "stock": 100}]'),

-- Ready To Use
('Pure Ghee', 'ready-to-use', 'స్వచ్ఛమైన నెయ్యి', 'Traditional clarified butter made from pure cow''s milk. Rich in vitamins A, D, E, and K, our ghee is perfect for cooking, tempering, and adding authentic flavor to your meals.', './images/products/ghee.jpg', '/images/products/ghee-detail.jpg', 500, '500ml', 50, '[{"quantity": "500ml", "price": 500, "mrp": 500, "stock": 50}]'),
('Multigrain Atta', 'ready-to-use', 'మల్టిగ్రెయిన్ ఆటా', 'A nutritious blend of wheat, millet, barley, and other wholesome grains. Perfect for making healthy rotis, parathas, and bread with enhanced nutritional value.', './images/products/multigrain-atta.jpg', '/images/products/multigrain-atta-detail.jpg', 60, '1kg', 100, '[{"quantity": "1kg", "price": 60, "mrp": 60, "stock": 100}]'),
('Premium Coffee', 'ready-to-use', 'ప్రీమియం కాఫీ', 'Aromatic South Indian filter coffee blend made from carefully selected coffee beans. Rich, smooth, and perfect for your morning ritual or evening relaxation.', './images/products/coffee.jpg', '/images/products/coffee-detail.jpg', 200, '250g', 100, '[{"quantity": "250g", "price": 200, "mrp": 200, "stock": 100}]'),
('Pure Pasupu', 'ready-to-use', 'స్వచ్ఛమైన పసుపు', 'Premium quality turmeric powder with high curcumin content. Known for its anti-inflammatory and antioxidant properties, perfect for cooking and health benefits.', './images/products/pasupu.jpg', '/images/products/pasupu-detail.jpg', 100, '250g', 100, '[{"quantity": "250g", "price": 100, "mrp": 100, "stock": 100}]');
